config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    get 'password_resets/new'
    get 'password_resets/edit'
    resources :password_resets, only: [:new, :create, :edit, :update]
    get 'home/index'
    resources :posts
    root 'static_pages#home', as: "home"
    get 'static_pages/help', as: "help"

    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    resources :users do
      member do
        get :following, :followers
      end
    end

    resources :users
    resources :account_activations, only: :edit
    resources :microposts, only: %i(create destroy)
    resources :relationships, only: %i(create destroy)
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to t(:h_title) , "#", id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
      <li><%= link_to t(:home), home_path %></li>
      <li><%= link_to t(:help), help_path %></li>

      <% if logged_in? %>
        <li><%= link_to t(:users), users_path %></li>
        <li class="dropdown">
          <%= link_to "#", class: "dropdown-toggle", "data-toggle": "dropdown" do %>
            <%= t(:account) %>
            <b class="caret"></b>
          <% end %>
          <ul class="dropdown-menu">
            <li><%= link_to t(:profile), current_user %></li>
            <li><%= link_to t(:settings), edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li> <%= link_to t(:log_out), logout_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><%= link_to t(:log_in), login_path %></li>
      <% end %>

      <li><%= link_to t(:c_en), locale: :en %></li>
      <li><%= link_to t(:c_ja), locale: :ja %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_nagivation_links.html.erb
<li><%= link_to t(:users), users_path %></li>

<%= content_tag :li do %>
  <%= link_to 'Switch to English', locale:en %>
<%= end unless current_page?(locale:en) %>

<%= content_tag :li do %>
  <%= link_to 'Switch to Japanese', locale:ja %>
<%= end unless current_page?(locale:ja) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | <%= t :l_title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: 'all', "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>